version: '3.7'
services :
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: creditSystem
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5050:8080